<a href="https://colab.research.google.com/github/a050e114/AI/blob/master/Numpy_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

x = np.linspace(2.0, 3.0, num=5)

y = np.linspace(2.0, 3.0, num=5, endpoint=False)

z = np.linspace(2.0, 3.0, num=5, retstep=True)

print(x)
print(y)
print(z)

[2.   2.25 2.5  2.75 3.  ]
[2.  2.2 2.4 2.6 2.8]
(array([2.  , 2.25, 2.5 , 2.75, 3.  ]), 0.25)


In [4]:
import numpy as np

a=np.array([[0,1],[2,3]])

a


array([[0, 1],
       [2, 3]])

In [5]:
import numpy as np

a=np.array([[0,1],[2,3]])

a.reshape(1,4)



array([[0, 1, 2, 3]])

In [6]:
import numpy as np

a=np.array([[0,1],[2,3]])

a.reshape(4,1)


array([[0],
       [1],
       [2],
       [3]])

In [16]:
import numpy as np

x = np.array([[2,10],[2,4]])

x




array([[ 2, 10],
       [ 2,  4]])

In [12]:
import numpy as np

x = np.array([[2,10],[4,2]])

x

array([[ 2, 10],
       [ 4,  2]])

In [20]:
import numpy as np

x = np.arange(24).reshape(4,3,2)

x

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [21]:
import numpy as np

x = np.arange(24).reshape(3,4,2)

x

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]])

In [22]:
import numpy as np


x = a=np.array([[0,1],[2,3]])

x

array([[0, 1],
       [2, 3]])

In [27]:
import numpy as np


x = a=np.array([[0,1],[2,3]])

a.reshape(1,4)



array([[0, 1, 2, 3]])

In [26]:
import numpy as np


x = a=np.array([[0,1],[2,3]])

a.reshape(4,1)



array([[0],
       [1],
       [2],
       [3]])

In [28]:
ar=np.array([np.arange(1,6),np.arange(10,15)]); 

ar


array([[ 1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14]])

In [29]:
ar=np.array([np.arange(1,6),np.arange(10,15)]); 

ar.ravel()



array([ 1,  2,  3,  4,  5, 10, 11, 12, 13, 14])

In [30]:
ar=np.array([np.arange(1,6),np.arange(10,15)]); 

ar.T.ravel()



array([ 1, 10,  2, 11,  3, 12,  4, 13,  5, 14])